services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-movies-web
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/app
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge
