services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-movies-web
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge